version: "3.2"
services:
  app:
    container_name: weatherapi-container
    restart: always
    build: .
    ports:
      - '3500:3500'
    links: 
      - mongo
  mongo:
    image: mongo
    container_name: weatherapi-database
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: weatherapi-container
      MONGO_INITDB_ROOT_USERNAME: weatherapi_user
      MONGO_INITDB_ROOT_PASSWORD: weatherapi_password
